### Define Logger config file directory ###
logging:
  config: classpath:logger${os.separator}log4j2-${spring.profiles.active}.yml # this is only for development
### application settings ###
spring:
  aop:
    proxy-target-class: true
  main:
    banner-mode: 'off' #disable banner
  jmx:
    enabled: false
  ### disable spring-boot's multipath resolver ###
  servlet:
    multipart:
      enabled: false
  ### Set the active profile here ###
  profiles:
    active: prd