### application settings ###
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    proxy-target-class: true
  main:
    banner-mode: 'off' #disable banner
  jmx:
    enabled: false
  ### disable spring-boot's multipath resolver ###
  servlet:
    multipart:
      enabled: false
  ### Set the active profile here ###
  profiles:
    active: dev
server:
  servlet:
    encoding:
      force: true